-- DDL ~1130AM


--1
CREATE  TABLE TB_CATEGORY(
NAME    VARCHAR2(10),
USE_YN  CHAR(1) DEFAULT 'Y'
);

--2
CREATE  TABLE TB_CLASS_TYPE(
NO  VARCHAR2(5) PRIMARY KEY,
NAME    VARCHAR2(10)
);

--3
ALTER   TABLE TB_CATEGORY
ADD PRIMARY KEY (NAME);

--4
ALTER   TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

--5
ALTER   TABLE TB_CLASS_TYPE
MODIFY (
        NO  VARCHAR2(10),
        NAME VARCHAR2(20)
);

ALTER   TABLE TB_CATEGORY
MODIFY (NAME VARCHAR2(20));

--6
ALTER   TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATRGORY_NAME;

ALTER   TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER   TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

SELECT *
FROM TB_CATEGORY;

--7
SELECT CONSTRAINT_NAME AS 이름,
CONSTRAINT_TYPE AS 유형,
COLUMN_NAME AS 컬럼,
R_CONSTRAINT_NAME AS 참조,
DELETE_RULE AS 삭제규칙
FROM USER_CONSTRAINTS
JOIN USER_CONS_COLUMNS
USING (CONSTRAINT_NAME, TABLE_NAME)
WHERE TABLE_NAME='TB_CLASS_TYPE'; 

SELECT * FROM USER_CONSTRAINTS
NATURAL JOIN SYS.USER_CONS_COLUMNS
WHERE TABLE_NAME = 'TB_CLASS_TYPE';

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007146 TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007141 TO PK_CLASS_TYPE_NO;

--8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT; 

--9
ALTER TABLE TB_CATEGORY
RENAME COLUMN CATRGORY_NAME TO CATEGORY_NAME;

ALTER TABLE TB_DEPARTMENT
ADD FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME) ;
















