--1
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '사학과';
-- 사학과 003
SELECT	COUNT(*) 학생수
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO = 003
AND		TO_CHAR(ENTRANCE_DATE,'RRRR')  = '2001';	

--2
SELECT	CATEGORY 계열,
		DEPARTMENT_NAME 학과이름,
		CAPACITY 정원
FROM		TB_DEPARTMENT
WHERE	CATEGORY LIKE '%공학%'
AND		(CAPACITY >= 20 AND CAPACITY <= 30)
ORDER BY	2;

--3
SELECT	CATEGORY,
		COUNT(*)
FROM		TB_DEPARTMENT
WHERE	CATEGORY LIKE '%학%'
GROUP BY	CATEGORY;

--4
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '영어영문학과';
-- 영어 002
SELECT	PROFESSOR_NAME 교수이름,
		SUBSTR(PROFESSOR_SSN,1,2) 출생년도,
		PROFESSOR_ADDRESS 주소
FROM		TB_PROFESSOR
WHERE	DEPARTMENT_NO = 002
ORDER BY 	2;

--5
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '국어국문학과';
-- 국어 001
SELECT	DEPARTMENT_NO,
		STUDENT_NAME,
		CASE ABSENCE_YN
		WHEN 'Y' THEN '휴학'
		WHEN 'N' THEN '정상'
		END AS 휴학여부		
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO = 001
AND		STUDENT_ADDRESS LIKE '%서울%'
ORDER BY	2;

--6
SELECT	SUBSTR(STUDENT_SSN,1,8)||'******' "(주민번호)",
		STUDENT_NAME 학생이름
FROM		TB_STUDENT
WHERE	SUBSTR(STUDENT_SSN,1,2) = 80
AND		SUBSTR(STUDENT_SSN,8,1) = 2
AND		STUDENT_NAME LIKE '김%';

--7
SELECT	DEPARTMENT_NAME 학과이름,
		CAPACITY 정원,
		CASE 
		WHEN CAPACITY >= 40 THEN '대강의실'
		WHEN CAPACITY >= 30 THEN '중강의실'
		ELSE '소강의실'
		END AS 강의실크기
FROM		TB_DEPARTMENT
WHERE	CATEGORY = '예체능'
ORDER BY	2 DESC;

--8
SELECT	STUDENT_NAME 이름,
		TO_CHAR(ENTRANCE_DATE,'RR"년" MM"월" DD"일"') 입학일자,
		TO_CHAR(SYSDATE,'RRRR') - TO_CHAR(ENTRANCE_DATE,'RRRR') "입학후기간(년)"
FROM		TB_STUDENT
WHERE	(STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE '인천%')
AND		TO_CHAR(ENTRANCE_DATE,'RRRR') < 2000
ORDER BY	3 DESC, 1;

--9
SELECT	DEPARTMENT_NO 학과번호,		
--		MIN(TO_CHAR(SYSDATE,'RRRR') - (19||SUBSTR(PROFESSOR_SSN,1,2))) 나이
		MIN((TO_CHAR(SYSDATE,'YY')+100) - SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM		TB_PROFESSOR
WHERE	PROFESSOR_ADDRESS LIKE '서울%'
GROUP BY	DEPARTMENT_NO
ORDER BY	2;

--10
SELECT	DEPARTMENT_NO 학과번호,
		STUDENT_NAME 학생이름,
		COACH_PROFESSOR_NO 지도교수번호,
		TO_CHAR(ENTRANCE_DATE,'RRRR')||'년' 입학년도
FROM		TB_STUDENT
WHERE	(ENTRANCE_DATE > '05/01/01' AND ENTRANCE_DATE < '06/12/31')
AND		STUDENT_ADDRESS IS NULL
AND		SUBSTR(STUDENT_SSN,8,1) = 1
ORDER BY	4;

--11

SELECT	SUBSTR(TERM_NO,1,4) 년도,
		ROUND ( AVG ( POINT ),2 ) 평점
FROM		TB_GRADE
JOIN		TB_STUDENT USING ( STUDENT_NO ) 
WHERE	COACH_PROFESSOR_NO = (
					SELECT	COACH_PROFESSOR_NO
					FROM		TB_STUDENT
					WHERE	STUDENT_NAME = '서가람'
					)
GROUP BY	SUBSTR(TERM_NO,1,4)
ORDER BY	1;

--12
SELECT	DEPARTMENT_NAME,
		STUDENT_NAME,
		ENTRANCE_DATE		
FROM		TB_STUDENT
JOIN		TB_DEPARTMENT USING ( DEPARTMENT_NO )
WHERE	(SUBSTR(STUDENT_SSN,8,1) = '1' OR SUBSTR(STUDENT_SSN,8,1) = '3')
AND		ABSENCE_YN = 'Y'
AND		ENTRANCE_DATE >= '2001/01/01'
ORDER BY	3 DESC;

--13
SELECT	PROFESSOR_NAME,
		COUNT(STUDENT_NO)
FROM		TB_PROFESSOR P
JOIN		TB_STUDENT S ON ( P.PROFESSOR_NO = S.COACH_PROFESSOR_NO )
LEFT JOIN	TB_CLASS_PROFESSOR USING ( PROFESSOR_NO )
WHERE	CLASS_NO IS NULL
GROUP BY 	PROFESSOR_NAME;

--14

SELECT	STUDENT_NAME 학생이름,
		TERM_NO 학기,
		ROUND ( AVG ( POINT ),1 ) 학점
FROM		TB_STUDENT
JOIN		TB_GRADE USING	( STUDENT_NO )
JOIN		TB_DEPARTMENT USING ( DEPARTMENT_NO )
WHERE	SUBSTR(TERM_NO,1,4) LIKE '2009%'
AND		CATEGORY = '공학'
GROUP BY	STUDENT_NAME, TERM_NO
HAVING	ROUND ( AVG ( POINT ),1 ) >= 4.0
ORDER BY	3 DESC, 1;

--15
SELECT	SUBSTR(TERM_NO,1,4) 년도,
		SUBSTR(TERM_NO,5,2) 학기,
		ROUND ( AVG ( POINT ),1 ) 평점
FROM		TB_GRADE
JOIN		TB_STUDENT USING ( STUDENT_NO )
JOIN		TB_DEPARTMENT USING ( DEPARTMENT_NO )
WHERE	DEPARTMENT_NO = (
						SELECT	DEPARTMENT_NO
						FROM		TB_DEPARTMENT
						JOIN		TB_STUDENT USING ( DEPARTMENT_NO )
						WHERE	STUDENT_NAME = '김고운'
						)
AND		SUBSTR(TERM_NO,1,4) IN ('2007','2008')						
GROUP BY	ROLLUP ( SUBSTR(TERM_NO,1,4)) , ROLLUP (SUBSTR(TERM_NO,5,2) )	
ORDER BY	1,2;

--16
SELECT	*
FROM		TB_CLASS
WHERE	CLASS_NAME = '문학과생태학';

SELECT	SUBSTR(TERM_NO, 1, 4) 년도,
		SUBSTR(TERM_NO, 5, 2) 학기,
		ROUND (AVG ( POINT ), 1 ) 평점
FROM		TB_GRADE G
JOIN		TB_STUDENT S USING ( STUDENT_NO )
WHERE	SUBSTR(TERM_NO, 1, 4) = '2004'
AND		S.DEPARTMENT_NO = (
					SELECT	DEPARTMENT_NO
					FROM		TB_CLASS
					WHERE	CLASS_NAME = '문학과생태학'
						)
GROUP BY	 SUBSTR(TERM_NO, 1, 4), ROLLUP( SUBSTR(TERM_NO, 5, 2)) ;


--17
SELECT	STUDENT_NAME,
		PROFESSOR_NAME		
FROM		TB_STUDENT S
JOIN		TB_PROFESSOR P ON ( S.COACH_PROFESSOR_NO = P.PROFESSOR_NO )
WHERE	STUDENT_NO LIKE 'A__3___'
AND		PROFESSOR_NAME LIKE '이%'
ORDER BY	1;

--18
SELECT	*
FROM		TB_DEPARTMENT
WHERE	CATEGORY IN ('예체능','의학');

SELECT	CATEGORY 계열,
		DEPARTMENT_NAME 학과이름,
		COUNT(STUDENT_NO) 학생수
FROM		TB_DEPARTMENT
LEFT JOIN		TB_STUDENT USING ( DEPARTMENT_NO )
WHERE	CATEGORY IN ('예체능','의학')
GROUP BY	CATEGORY, DEPARTMENT_NAME
ORDER BY	1, 3 DESC;

SELECT CATEGORY,
        DEPARTMENT_NAME 학과명,
        COUNT(STUDENT_NO) AS 학생수
FROM TB_DEPARTMENT 
LEFT JOIN TB_STUDENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' OR CATEGORY= '의학'
GROUP BY  CATEGORY,  DEPARTMENT_NAME
ORDER BY 1, 3 DESC ;

--19
SELECT	C.CLASS_NAME,
		CC.CLASS_NAME
FROM		TB_DEPARTMENT D
JOIN		TB_CLASS C ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
JOIN		TB_CLASS CC ON (C.CLASS_NO = CC.PREATTENDING_CLASS_NO)
WHERE	DEPARTMENT_NAME = '행정학과';

SELECT	CLASS_NAME,
		(
		SELECT	CLASS_NAME 
		FROM		TB_CLASS		
		WHERE	C.PREATTENDING_CLASS_NO = CLASS_NO
		
		) AS 과목
FROM		TB_DEPARTMENT
JOIN		TB_CLASS C USING(DEPARTMENT_NO)-- ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)

WHERE	DEPARTMENT_NAME = '행정학과'
AND		C.PREATTENDING_CLASS_NO IS NOT NULL;










