--1
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '사학과';
-- 사학과 003
SELECT	COUNT(*) 학생수
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO = 003
AND		TO_CHAR(ENTRANCE_DATE,'RRRR')  = '2001';	

--2
SELECT	CATEGORY 계열,
		DEPARTMENT_NAME 학과이름,
		CAPACITY 정원
FROM		TB_DEPARTMENT
WHERE	CATEGORY LIKE '%공학%'
AND		(CAPACITY >= 20 AND CAPACITY <= 30)
ORDER BY	2;

--3
SELECT	CATEGORY,
		COUNT(*)
FROM		TB_DEPARTMENT
WHERE	CATEGORY LIKE '%학%'
GROUP BY	CATEGORY;

--4
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '영어영문학과';
-- 영어 002
SELECT	PROFESSOR_NAME 교수이름,
		SUBSTR(PROFESSOR_SSN,1,2) 출생년도,
		PROFESSOR_ADDRESS 주소
FROM		TB_PROFESSOR
WHERE	DEPARTMENT_NO = 002
ORDER BY 	2;

--5
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '국어국문학과';
-- 국어 001
SELECT	DEPARTMENT_NO,
		STUDENT_NAME,
		CASE ABSENCE_YN
		WHEN 'Y' THEN '휴학'
		WHEN 'N' THEN '정상'
		END AS 휴학여부		
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO = 001
AND		STUDENT_ADDRESS LIKE '%서울%'
ORDER BY	2;

--6
SELECT	SUBSTR(STUDENT_SSN,1,8)||'******' "(주민번호)",
		STUDENT_NAME 학생이름
FROM		TB_STUDENT
WHERE	SUBSTR(STUDENT_SSN,1,2) = 80
AND		SUBSTR(STUDENT_SSN,8,1) = 2
AND		STUDENT_NAME LIKE '김%';

--7
SELECT	DEPARTMENT_NAME 학과이름,
		CAPACITY 정원,
		CASE 
		WHEN CAPACITY >= 40 THEN '대강의실'
		WHEN CAPACITY >= 30 THEN '중강의실'
		ELSE '소강의실'
		END AS 강의실크기
FROM		TB_DEPARTMENT
WHERE	CATEGORY = '예체능'
ORDER BY	2 DESC;

--8
SELECT	STUDENT_NAME 이름,
		TO_CHAR(ENTRANCE_DATE,'RR"년" MM"월" DD"일"') 입학일자,
		TO_CHAR(SYSDATE,'RRRR') - TO_CHAR(ENTRANCE_DATE,'RRRR') "입학후기간(년)"
FROM		TB_STUDENT
WHERE	(STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE '인천%')
AND		TO_CHAR(ENTRANCE_DATE,'RRRR') < 2000
ORDER BY	3 DESC, 1;

--9
SELECT	DEPARTMENT_NO 학과번호,		
--		MIN(TO_CHAR(SYSDATE,'RRRR') - (19||SUBSTR(PROFESSOR_SSN,1,2))) 나이
		MIN((TO_CHAR(SYSDATE,'YY')+100) - SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM		TB_PROFESSOR
WHERE	PROFESSOR_ADDRESS LIKE '서울%'
GROUP BY	DEPARTMENT_NO
ORDER BY	2;

--10
SELECT	DEPARTMENT_NO 학과번호,
		STUDENT_NAME 학생이름,
		COACH_PROFESSOR_NO 지도교수번호,
		TO_CHAR(ENTRANCE_DATE,'RRRR')||'년' 입학년도
FROM		TB_STUDENT
WHERE	(ENTRANCE_DATE > '05/01/01' AND ENTRANCE_DATE < '06/12/31')
AND		STUDENT_ADDRESS IS NULL
AND		SUBSTR(STUDENT_SSN,8,1) = 1
ORDER BY	4;



















