-- WORKSHOP2
--1
SELECT	STUDENT_NO 학번,
		STUDENT_NAME 이름,
		ENTRANCE_DATE 입학년도
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO IN ('002')
ORDER BY	3;

--2
SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM		TB_PROFESSOR
WHERE	LENGTH(PROFESSOR_NAME) <> 3;

--3
SELECT	PROFESSOR_NAME 교수이름,
		TO_CHAR(SYSDATE,'RRRR') - ('19'||SUBSTR(PROFESSOR_SSN,1,2)) 나이 
FROM		TB_PROFESSOR
WHERE	SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY	2;

-- ************************************************
-- WORKSHOP3

--1
SELECT	STUDENT_NAME 학생이름,
		STUDENT_ADDRESS 주소지
FROM		TB_STUDENT
ORDER BY	1;

--2
SELECT	STUDENT_NAME,
		STUDENT_SSN
FROM		TB_STUDENT
WHERE	ABSENCE_YN = 'Y'
ORDER BY 	2 DESC;

--3
SELECT	STUDENT_NAME,
		STUDENT_NO,
		STUDENT_ADDRESS
FROM		TB_STUDENT
WHERE	STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%'
AND		STUDENT_NO NOT LIKE 'A%'
ORDER BY 	1;

--4
SELECT	DEPARTMENT_NO
FROM		TB_DEPARTMENT
WHERE	DEPARTMENT_NAME = '법학과';

SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM		TB_PROFESSOR
WHERE	DEPARTMENT_NO = 005
ORDER BY	2;

--5
SELECT	S.STUDENT_NO,
		TO_CHAR(POINT,'9.99') POINT
FROM		TB_STUDENT S
JOIN		TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE	TERM_NO = '200402'
AND		CLASS_NO = 'C3118100'
ORDER BY	2 DESC;

--6
SELECT	STUDENT_NO,
		STUDENT_NAME,
		DEPARTMENT_NAME
FROM		TB_STUDENT S, TB_DEPARTMENT D
WHERE	S.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY	2;

--7
SELECT	CLASS_NAME,
		DEPARTMENT_NAME
FROM		TB_CLASS C, TB_DEPARTMENT D
WHERE	C.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY	2;

--8
SELECT	CLASS_NAME,
		PROFESSOR_NAME
FROM		TB_CLASS
JOIN		TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN		TB_PROFESSOR USING (PROFESSOR_NO);

--9
SELECT	CLASS_NAME,
		PROFESSOR_NAME
FROM		TB_CLASS C
JOIN		TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
JOIN		TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO)
JOIN		TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE	CATEGORY = '인문사회';
































