--1
SELECT	STUDENT_NO 학번,
		STUDENT_NAME 이름,
		ENTRANCE_DATE 입학년도
FROM		TB_STUDENT
WHERE	DEPARTMENT_NO IN ('002')
ORDER BY	3;

--2
SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM		TB_PROFESSOR
WHERE	LENGTH(PROFESSOR_NAME) <> 3;

--3
SELECT	PROFESSOR_NAME 교수이름,
		TO_CHAR(SYSDATE,'RRRR') - TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN,1,2),'RR'),'RRRR') 나이 
FROM		TB_PROFESSOR
WHERE	SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY	2;