-- WORKSHOP2 복습

--1
SELECT  STUDENT_NO 학번,
        STUDENT_NAME 이름,
        TO_CHAR(ENTRANCE_DATE,'RRRR-MM-DD') 입학년도
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO = '002'
ORDER BY 1;

--2
SELECT  PROFESSOR_NAME,
        PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   LENGTH(PROFESSOR_NAME) != 3;

--3
SELECT  PROFESSOR_NAME 교수이름,
        TO_CHAR(SYSDATE,'RRRR') - (19 ||(SUBSTR(PROFESSOR_SSN,1,2) )) 나이,
        PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY  2,1;

--4
SELECT  SUBSTR(PROFESSOR_NAME,2) 이름
FROM    TB_PROFESSOR;

--5
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
WHERE   TO_CHAR(ENTRANCE_DATE,'RRRR') - TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR'),'RRRR')   > 19
ORDER BY 1;

--6
SELECT  TO_CHAR(TO_DATE('20201225','RRRRMMDD'),'DAY') "2020 크리스마스"
FROM    DUAL;

--7
SELECT  TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'YYYY/MM/DD')
FROM    DUAL;

--8
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
WHERE   STUDENT_NO NOT LIKE 'A%'
ORDER BY 1;

--9
SELECT  ROUND(AVG(POINT),1) 평점
FROM    TB_GRADE
WHERE   STUDENT_NO IN ('A517178');

--10
SELECT  DEPARTMENT_NO "학과 번호",
        COUNT(*) "학생수(명)"
FROM    TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11
SELECT  COUNT(*)
FROM    TB_STUDENT
WHERE   COACH_PROFESSOR_NO IS NULL;

--12
SELECT  SUBSTR(TERM_NO,1,4) 연도,
        ROUND(AVG(POINT),1) "연도 별 평점"
FROM    TB_GRADE
WHERE   STUDENT_NO IN ('A112113')
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13
SELECT  DEPARTMENT_NO 학과코드명,
        SUM(CASE ABSENCE_YN
            WHEN 'Y' THEN 1
            WHEN 'N' THEN 0
            END)    AS "휴학생 수" 
FROM    TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14
SELECT  STUDENT_NAME,
        COUNT(STUDENT_NAME)
FROM    TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY 1;

--15
SELECT  DECODE(SUBSTR(TERM_NO,1,4),NULL,'합계',SUBSTR(TERM_NO,1,4)) 연도, 
        SUBSTR(TERM_NO,5,2) 학기,
        ROUND(AVG(POINT),1) 평점
FROM    TB_GRADE
WHERE   STUDENT_NO IN('A112113')
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));


































