-- DDL 


--1
CREATE  TABLE TB_CATEGORY(
NAME    VARCHAR2(10),
USE_YN  CHAR(1) DEFAULT 'Y'
);

--2
CREATE  TABLE TB_CLASS_TYPE(
NO  VARCHAR2(5) PRIMARY KEY,
NAME    VARCHAR2(10)
);

--3
ALTER   TABLE TB_CATEGORY
ADD PRIMARY KEY (NAME);

--4
ALTER   TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

--5
ALTER   TABLE TB_CLASS_TYPE
MODIFY (
        NO  VARCHAR2(10),
        NAME VARCHAR2(20)
);

ALTER   TABLE TB_CATEGORY
MODIFY (NAME VARCHAR2(20));

--6
ALTER   TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATRGORY_NAME;

ALTER   TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER   TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

SELECT *
FROM TB_CATEGORY;

--7
SELECT CONSTRAINT_NAME AS 이름,
CONSTRAINT_TYPE AS 유형,
COLUMN_NAME AS 컬럼,
R_CONSTRAINT_NAME AS 참조,
DELETE_RULE AS 삭제규칙
FROM USER_CONSTRAINTS
JOIN USER_CONS_COLUMNS
USING (CONSTRAINT_NAME, TABLE_NAME)
WHERE TABLE_NAME='TB_CLASS_TYPE'; 

SELECT * FROM USER_CONSTRAINTS
NATURAL JOIN SYS.USER_CONS_COLUMNS
WHERE TABLE_NAME = 'TB_CLASS_TYPE';

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007146 TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007141 TO PK_CLASS_TYPE_NO;

--8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT; 

--9
ALTER TABLE TB_CATEGORY
RENAME COLUMN CATRGORY_NAME TO CATEGORY_NAME;

ALTER TABLE TB_DEPARTMENT
ADD FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME) ;

--10
CREATE VIEW VW_학생일반정보
AS	
	SELECT	STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
	FROM	  	TB_STUDENT;
	
SELECT * FROM VW_학생일반정보;

--11
DROP VIEW VW_지도면담;

CREATE VIEW VW_지도면담
AS
SELECT	STUDENT_NAME,
		DEPARTMENT_NAME,
		PROFESSOR_NAME
FROM		TB_STUDENT S
JOIN		TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN		TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
ORDER BY	2;

SELECT *
FROM "VW_지도면담";

--12
CREATE VIEW VW_학과별학생수
AS
SELECT	DEPARTMENT_NAME,
		COUNT(STUDENT_NO) "STUDENT_COUNT"
FROM		TB_STUDENT
JOIN		TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY	DEPARTMENT_NAME;

SELECT *
FROM "VW_학과별학생수";

--13
SELECT 	* 
FROM		TB_STUDENT
WHERE	STUDENT_NO = 'A213046';

UPDATE	"VW_학생일반정보"
SET		STUDENT_NAME = '윤석호'
WHERE	STUDENT_NO = 'A213046'	;

--14
CREATE VIEW VW_학생일반정보2
AS	
SELECT	STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM	  	TB_STUDENT
WITH READ ONLY;

--15
SELECT	C.CLASS_NO,
		C.CLASS_NAME,
		COUNT(S.STUDENT_NO)
FROM		TB_CLASS C
JOIN		TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN		TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN		TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE	TERM_NO LIKE '2006%' OR TERM_NO LIKE '2008%' OR TERM_NO LIKE '2007%'
GROUP BY	C.CLASS_NO, C.CLASS_NAME
ORDER BY	3 DESC;

SELECT 	C.CLASS_NO, C.CLASS_NAME, COUNT(S.STUDENT_NO)
FROM 	TB_CLASS C
JOIN		TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
JOIN		TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
WHERE	TERM_NO BETWEEN 200601 AND 200903
GROUP BY 	C.CLASS_NO, C.CLASS_NAME
ORDER BY	3 DESC;

SELECT *
FROM (
	SELECT 	C.CLASS_NO, C.CLASS_NAME, COUNT(S.STUDENT_NO)
	FROM 	TB_CLASS C
	JOIN		TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
	JOIN		TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
	WHERE	TERM_NO BETWEEN 200601 AND 200903
	GROUP BY 	C.CLASS_NO, C.CLASS_NAME
	ORDER BY	3 DESC
	)
WHERE	ROWNUM IN (1,2,3);	

-- DML

--1
CREATE TABLE TB_CLASS_TYPE
(CLASS_TYPE	VARCHAR2(15));
INSERT INTO TB_CLASS_TYPE VALUES('전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('전공선택');
INSERT INTO TB_CLASS_TYPE VALUES('교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('논문지도');

SELECT *
FROM TB_CLASS_TYPE;

--2
CREATE TABLE TB_학생일반정보
AS	SELECT	STUDENT_NO 학번,
			STUDENT_NAME 학생이름,
			STUDENT_ADDRESS 주소
	FROM		TB_STUDENT;
	
SELECT *
FROM "TB_학생일반정보";

--3
CREATE TABLE TB_국어국문학과
AS	SELECT	STUDENT_NO 학번,
			STUDENT_NAME 학생이름,
			TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR'),'RRRR')||'년' AS 출생년도,
			PROFESSOR_NAME 교수이름
	FROM		TB_STUDENT S
	LEFT JOIN	TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
	JOIN		TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
	WHERE	DEPARTMENT_NAME = '국어국문학과';
	
SELECT * 
FROM TB_국어국문학과;

--4
UPDATE	TB_DEPARTMENT
SET		CAPACITY = ROUND(CAPACITY * 1.1);
--ROLLBACK;


































