--WORKSHOP2

--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3
SELECT PROFESSOR_NAME 교수이름
FROM TB_PROFESSOR
WHERE professor_ssn LIKE '_______1%'
ORDER BY SUBSTR(PROFESSOR_SSN,1,2) DESC, professor_name ASC;

--4
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ADD_MONTHS(TO_DATE(1900+SUBSTR(STUDENT_SSN,1,2),'YYYY'),240) < ENTRANCE_DATE
ORDER BY STUDENT_NO ASC;

--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ADD_MONTHS(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RR'),240) < ENTRANCE_DATE;

--6
SELECT TO_CHAR(TO_DATE('2020-12-25','YYYY-MM-DD'),'DAY')
FROM DUAL;



