SELECT STUDENT_NO 학번,
       STUDENT_NAME 이름,
       ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM tb_professor
WHERE LENGTH(professor_name) != 3; 

SELECT PROFESSOR_NAME 교수이름
FROM TB_PROFESSOR
WHERE PROFESSOR_SSN LIKE '_______1%'
ORDER BY SUBSTR(PROFESSOR_SSN,1,2) DESC ,professor_name ASC;

SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

-- 수정요망 인출된 행의 개수 245
SELECT STUDENT_NO, STUDENT_NAME ,TO_DATE(SUBSTR(STUDENT_SSN,1,6)),ENTRANCE_DATE
FROM TB_STUDENT
WHERE MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE(SUBSTR(STUDENT_SSN,1,6)))/12 > 19
ORDER BY STUDENT_NO ASC;

SELECT STUDENT_NO, STUDENT_NAME ,TO_DATE(SUBSTR(STUDENT_SSN,1,6)),ENTRANCE_DATE
FROM TB_STUDENT
WHERE ADD_MONTHS(ENTRANCE_DATE, -228) > TO_DATE(SUBSTR(STUDENT_SSN,1,6)); 

