--WORKSHOP4

-- 16
SELECT      CLASS_NO,
                CLASS_NAME,
                AVG(POINT)
FROM        TB_CLASS A
JOIN          TB_GRADE USING (CLASS_NO)
RIGHT JOIN  TB_DEPARTMENT D ON (A.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE       D.DEPARTMENT_NAME = '환경조경학과'  AND A.CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

--17
SELECT  STUDENT_NAME, STUDENT_ADDRESS            
FROM    TB_STUDENT
JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE   DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME
                                                FROM TB_STUDENT
                                                JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                                                WHERE STUDENT_NAME = '최경희'    );
                                                
--18
SELECT	STUDENT_NO, STUDENT_NAME
FROM		(
		SELECT	STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),2)
		FROM		TB_STUDENT
		JOIN		TB_GRADE USING (STUDENT_NO)
		JOIN		TB_DEPARTMENT USING (DEPARTMENT_NO)
		WHERE	DEPARTMENT_NAME = '국어국문학과'
		GROUP BY	STUDENT_NO, STUDENT_NAME
		ORDER BY	3 DESC
		)
WHERE	ROWNUM = 1;

--19
SELECT	DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) 전공평점
FROM		TB_DEPARTMENT
JOIN		TB_STUDENT USING (DEPARTMENT_NO)
JOIN		TB_GRADE USING (STUDENT_NO)
WHERE	CATEGORY = (
	SELECT	CATEGORY
	FROM		TB_DEPARTMENT
	WHERE	DEPARTMENT_NAME = '환경조경학과'
					)
GROUP BY 	DEPARTMENT_NAME
ORDER BY	1;			

--4. 현 학과들의 정원을 10% 증가시키게 되었다. 이에 사용할 SQL 문을 작성하시오. (단,
--반올림을 사용하여 소수점 자릿수는 생기지 않도록 한다)

SELECT	DEPARTMENT_NAME 학과, CAPACITY 기존, ROUND(CAPACITY * 1.1) 변경
FROM 	TB_DEPARTMENT;

--5. 학번 A413042 인 박건우 학생의 주소가 "서울시 종로구 숭인동 181-21 "로 변경되었다고
--한다. 주소지를 정정하기 위해 사용할 SQL 문을 작성하시오.

UPDATE	TB_STUDENT
SET		STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE	STUDENT_NO = 'A413042';

SELECT
	*
FROM TB_STUDENT
WHERE STUDENT_NAME = '박건우';

--6. 주민등록번호 보호법에 따라 학생정보 테이블에서 주민번호 뒷자리를 저장하지 않기로
--결정하였다. 이 내용을 반영한 적절한 SQL 문장을 작성하시오.
--(예. 830530-2124663 ==> 830530 )

UPDATE	TB_STUDENT
SET		STUDENT_SSN = RPAD(SUBSTR(STUDENT_SSN,1,8),14,'*');

SELECT *
FROM TB_STUDENT;

--7. 의학과 김명훈 학생은 2005 년 1 학기에 자신이 수강한 '피부생리학' 점수가
--잘못되었다는 것을 발견하고는 정정을 요청하였다. 담당 교수의 확인 받은 결과 해당
--과목의 학점을 3.5 로 변경키로 결정되었다. 적절한 SQL 문을 작성하시오.

UPDATE TB_GRADE
SET	POINT = 3.5
WHERE STUDENT_NO = (
	SELECT	STUDENT_NO
	FROM		TB_STUDENT
	JOIN		TB_DEPARTMENT USING (DEPARTMENT_NO)
	WHERE	STUDENT_NAME = '김명훈'
	AND		DEPARTMENT_NAME = '의학과'
				)
AND	TERM_NO = '200501'
AND	CLASS_NO = (
	SELECT	CLASS_NO
	FROM		TB_CLASS
	WHERE	CLASS_NAME = '피부생리학'
				);

SELECT *
FROM TB_GRADE
WHERE STUDENT_NO = 'A331101';
--8. 성적 테이블(TB_GRADE) 에서 휴학생들의 성적항목을 제거하시오
UPDATE TB_GRADE
SET POINT = NULL
WHERE STUDENT_NO IN (
	SELECT STUDENT_NO
	FROM TB_STUDENT
	WHERE ABSENCE_YN = 'Y'
);

SELECT *
FROM TB_GRADE
WHERE STUDENT_NO IN (
	SELECT STUDENT_NO
	FROM TB_STUDENT
	WHERE ABSENCE_YN = 'Y'
				);
