--1
SELECT  STUDENT_NAME "학생 이름",
        STUDENT_ADDRESS 주소지
FROM    TB_STUDENT
ORDER BY 1;

--2
SELECT  STUDENT_NAME,
        STUDENT_SSN
FROM    TB_STUDENT
WHERE   ABSENCE_YN = 'Y'
ORDER BY TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD') DESC;

--3
SELECT  STUDENT_NAME 학생이름,
        STUDENT_NO 학번,
        STUDENT_ADDRESS "거주지 주소"
FROM    TB_STUDENT
WHERE   (STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE '강원%') AND STUDENT_NO NOT LIKE 'A%';

--4
SELECT  PROFESSOR_NAME,
		PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   DEPARTMENT_NO = '005'
ORDER BY TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD');

--4 JOIN 사용
SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM	TB_PROFESSOR P
JOIN	TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE	D.DEPARTMENT_NO = (	SELECT	DEPARTMENT_NO
								FROM	TB_DEPARTMENT
								WHERE	DEPARTMENT_NAME = '법학과')
ORDER BY TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD');								

--5
SELECT  STUDENT_NO,
        TO_CHAR(POINT,'9.99')
FROM    TB_GRADE
WHERE   CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC;

--6
SELECT  STUDENT_NO,
        STUDENT_NAME,
        DEPARTMENT_NAME        
FROM    TB_STUDENT
JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7
SELECT  CLASS_NAME,
        DEPARTMENT_NAME
FROM    TB_CLASS
JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7
SELECT  CLASS_NAME,
        DEPARTMENT_NAME
FROM    TB_CLASS A,
        TB_DEPARTMENT B
WHERE   A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY 2;



--8
SELECT   CLASS_NAME,
		 PROFESSOR_NAME
FROM    TB_CLASS
JOIN     TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN     TB_PROFESSOR USING(PROFESSOR_NO);


--9
SELECT   A.CLASS_NAME,
		C.PROFESSOR_NAME
FROM     TB_CLASS A
JOIN     TB_CLASS_PROFESSOR B ON(A.CLASS_NO = B.CLASS_NO)
JOIN     TB_PROFESSOR C ON(B.PROFESSOR_NO = C.PROFESSOR_NO)
JOIN     TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE  CATEGORY = '인문사회';
-- 수정중!!
SELECT   CLASS_NAME,
		 PROFESSOR_NAME
FROM    TB_CLASS
JOIN     TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN     TB_PROFESSOR USING (PROFESSOR_NO)
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE 	CATEGORY = '인문사회';

--10
SELECT  A.STUDENT_NO,
        A.STUDENT_NAME,
        ROUND(AVG(B.POINT),1)
FROM    TB_STUDENT A
JOIN    TB_GRADE B ON(A.STUDENT_NO = B.STUDENT_NO)
WHERE   A.DEPARTMENT_NO = '059'
GROUP BY A.STUDENT_NO, A.STUDENT_NAME
ORDER BY 3 DESC;

--11
SELECT  B.DEPARTMENT_NAME,
        A.STUDENT_NAME,
        C.PROFESSOR_NAME
FROM    TB_STUDENT A
JOIN    TB_DEPARTMENT B ON (A.DEPARTMENT_NO = B.DEPARTMENT_NO)
JOIN    TB_PROFESSOR C ON (A.COACH_PROFESSOR_NO = C.PROFESSOR_NO)
WHERE   A.STUDENT_NO = 'A313047';

--12
SELECT  DISTINCT A.STUDENT_NAME,
        B.TERM_NO
FROM    TB_STUDENT A
JOIN    TB_GRADE B ON (A.STUDENT_NO = B.STUDENT_NO)
JOIN    TB_CLASS C ON (A.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE   B.CLASS_NO = 'C2604100' AND B.TERM_NO LIKE '2007%'
ORDER BY 1;

--13
SELECT  CLASS_NAME,
		DEPARTMENT_NAME
FROM   TB_CLASS A
JOIN    	TB_DEPARTMENT B ON (A.DEPARTMENT_NO = B.DEPARTMENT_NO)
LEFT    	JOIN TB_CLASS_PROFESSOR C USING (CLASS_NO)
WHERE  CATEGORY LIKE '예체능%' AND PROFESSOR_NO IS NULL
ORDER BY 2 , 1 ;

--14
SELECT	S.STUDENT_NAME 학생이름,
		NVL(P.PROFESSOR_NAME,'지도교수 미지정') 지도교수		
FROM	TB_STUDENT S
LEFT JOIN	TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN	TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE	D.DEPARTMENT_NAME LIKE '서반아%'
ORDER BY S.ENTRANCE_DATE;

--15
SELECT	STUDENT_NO 학번,
		STUDENT_NAME 이름,
		DEPARTMENT_NAME 학과이름,
		ROUND(AVG(POINT),1) 평점
FROM	TB_STUDENT
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN	TB_GRADE USING (STUDENT_NO)
WHERE	ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING	AVG(POINT) >= 4.0
ORDER BY 1;

--16
SELECT	CLASS_NO,
		CLASS_NAME,
		AVG(POINT)
FROM	TB_CLASS
JOIN	TB_GRADE USING (CLASS_NO)
WHERE	DEPARTMENT_NO = (		SELECT	DEPARTMENT_NO
								FROM	TB_DEPARTMENT
								WHERE	DEPARTMENT_NAME = '환경조경학과')
AND	CLASS_TYPE LIKE '전공%'								
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

--17
--SELECT	DEPARTMENT_NO
--FROM	TB_STUDENT S, TB_DEPARTMENT D
--WHERE	S.DEPARTMENT_NO = D.DEPARTMENT_NO
--AND	STUDENT_NAME = '최경희'

SELECT	STUDENT_NAME,
		STUDENT_ADDRESS
FROM	TB_STUDENT 
WHERE	DEPARTMENT_NO = (SELECT	S.DEPARTMENT_NO
							FROM	TB_STUDENT S, TB_DEPARTMENT D
							WHERE	S.DEPARTMENT_NO = D.DEPARTMENT_NO
							AND	STUDENT_NAME = '최경희');
							
--18
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN    TB_GRADE USING (STUDENT_NO)
WHERE   DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO,STUDENT_NAME
HAVING AVG(POINT) = (   SELECT  MAX(AVG(POINT))
                        FROM    TB_GRADE
                        JOIN    TB_STUDENT USING (STUDENT_NO)
                        JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
                        WHERE   DEPARTMENT_NAME = '국어국문학과'
                        GROUP BY STUDENT_NO);

--19
SELECT  DEPARTMENT_NAME,
        ROUND(AVG(POINT),1)
FROM    TB_DEPARTMENT
JOIN    TB_CLASS USING (DEPARTMENT_NO)
JOIN    TB_GRADE USING (CLASS_NO)
WHERE   CATEGORY = (SELECT  CATEGORY
                    FROM    TB_DEPARTMENT
                    WHERE   DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;

SELECT  CATEGORY
FROM    TB_DEPARTMENT
WHERE   DEPARTMENT_NAME = '환경조경학과';
















         















