--1
SELECT  STUDENT_NAME "학생 이름",
            STUDENT_ADDRESS 주소지
FROM    TB_STUDENT
ORDER BY 1;

--2
SELECT  STUDENT_NAME,
            STUDENT_SSN
FROM    TB_STUDENT
WHERE   ABSENCE_YN = 'Y'
ORDER BY TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD') DESC;

--3
SELECT  STUDENT_NAME 학생이름,
            STUDENT_NO 학번,
            STUDENT_ADDRESS "거주지 주소"
FROM    TB_STUDENT
WHERE   (STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE '강원%') AND STUDENT_NO NOT LIKE 'A%';

--4
SELECT  PROFESSOR_NAME,
            PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   DEPARTMENT_NO = '005'
ORDER BY TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD');

--5
SELECT   STUDENT_NO,
             TO_CHAR(POINT,'9.99')
FROM    TB_GRADE
WHERE   CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC;

--6
SELECT  STUDENT_NO,
        STUDENT_NAME,
        DEPARTMENT_NAME        
FROM   TB_STUDENT
JOIN     TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7
SELECT  CLASS_NAME,
        DEPARTMENT_NAME
FROM   TB_CLASS
JOIN    TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7
SELECT  CLASS_NAME,
        DEPARTMENT_NAME
FROM    TB_CLASS A,
        TB_DEPARTMENT B
WHERE   A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY 2;



--8
SELECT   CLASS_NAME,
         PROFESSOR_NAME
FROM     TB_CLASS
JOIN     TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN     TB_PROFESSOR USING(PROFESSOR_NO);

--9
SELECT   A.CLASS_NAME,
         C.PROFESSOR_NAME
FROM     TB_CLASS A
JOIN     TB_CLASS_PROFESSOR B ON(A.CLASS_NO = B.CLASS_NO)
JOIN     TB_PROFESSOR C ON(B.PROFESSOR_NO = C.PROFESSOR_NO)
JOIN     TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE    D.CATEGORY = '인문사회';

--10
SELECT  A.STUDENT_NO,
        A.STUDENT_NAME,
        ROUND(AVG(B.POINT),1)
FROM    TB_STUDENT A
JOIN    TB_GRADE B ON(A.STUDENT_NO = B.STUDENT_NO)
WHERE   A.DEPARTMENT_NO = '059'
GROUP BY A.STUDENT_NO, A.STUDENT_NAME
ORDER BY 3 DESC;

--11
SELECT  B.DEPARTMENT_NAME,
        A.STUDENT_NAME,
        C.PROFESSOR_NAME
FROM    TB_STUDENT A
JOIN    TB_DEPARTMENT B ON (A.DEPARTMENT_NO = B.DEPARTMENT_NO)
JOIN    TB_PROFESSOR C ON (A.COACH_PROFESSOR_NO = C.PROFESSOR_NO)
WHERE   A.STUDENT_NO = 'A313047';

--12
SELECT  DISTINCT A.STUDENT_NAME
       -- B.TERM_NO
FROM    TB_STUDENT A
JOIN    TB_GRADE B ON (A.STUDENT_NO = B.STUDENT_NO)
JOIN    TB_CLASS C ON (A.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE   B.CLASS_NO = 'C2604100' AND B.TERM_NO LIKE '2007%'
ORDER BY 1;











         















