-- DAY13

CREATE SEQUENCE SEQ_EMPID
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

SELECT SEQ_EMPID.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ2_EMPID
START WITH 5
INCREMENT BY 5
MAXVALUE 15
CYCLE
NOCACHE;

SELECT SEQ2_EMPID.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ3_EMPID
INCREMENT BY 5
START WITH 300 MAXVALUE 310
NOCYCLE NOCACHE;

SELECT SEQ3_EMPID.NEXTVAL FROM DUAL;
SELECT SEQ3_EMPID.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQID
INCREMENT BY 1
START WITH 300
MAXVALUE 310
NOCYCLE NOCACHE;

INSERT INTO EMPLOYEE (EMP_ID, EMP_NO, EMP_NAME)
VALUES (TO_CHAR(SEQID.NEXTVAL),
'850130-1558215', '김영민');
INSERT INTO EMPLOYEE (EMP_ID, EMP_NO, EMP_NAME)
VALUES (TO_CHAR(SEQID.NEXTVAL),
'840221-1361299', '구진표');
SELECT EMP_ID, EMP_NO, EMP_NAME
FROM EMPLOYEE
ORDER BY 1 DESC;

CREATE SEQUENCE SEQID2
INCREMENT BY 1
START WITH 300
MAXVALUE 310
NOCYCLE NOCACHE;

SELECT SEQID2.NEXTVAL FROM DUAL;
SELECT SEQID2.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEQID2
INCREMENT BY 5;
SELECT SEQID2.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ1
INCREMENT BY 1
START WITH 1
NOCACHE;
SELECT SEQ1.NEXTVAL FROM DUAL;
SELECT SEQ1.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ2
INCREMENT BY 1
START WITH 1
CACHE 5;
SELECT SEQ2.NEXTVAL FROM DUAL;
SELECT SEQ2.CURRVAL FROM DUAL;

SELECT SEQUENCE_NAME,
CACHE_SIZE,
LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('SEQ1','SEQ2');

-------------------------------------------------------------------------
-- 시퀀스 (SEQUENCE)
-- 자동 숫자 발생기
-- 순차적으로 정수 값을 자동으로 생성하는 객체

/*
형식
CREATE SEQUENCE 시퀀스이름
START WITH 시작값
INCREMENT BY 증가량|감소량
MAXVALUE 최대값 / NOMAXVALUE
MINVALUE 최소값 / NOMINVALUE
CYCLE / NOCYCLE
CACHE N개 / NOCACHE;

*/

-- 시퀀스 만들기
CREATE SEQUENCE SEQ_EMPID
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE     -- 310까지 생성 후 더 이상 숫자 생성하지 않겠다.
NOCACHE;   -- 미리 메모리에 숫자를 만들어 놓지 않겠다.

-- 데이터 딕셔너리 확인 : USER_SEQUENCES
DESC USER_SEQUENCES;

SELECT * FROM USER_SEQUENCES;

-- 시퀀스 객체 값 발생 : 시퀀스이름.NEXTVAL
SELECT SEQ_EMPID.NEXTVAL FROM DUAL;  -- 300

-- 시퀀스 객체가 가진 방금 발생시킨 값 조회 : 시퀀스이름.CURRVAL
SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 300

-- 시퀀스 만들기 2
CREATE SEQUENCE SEQ2_EMPID
START WITH 5
INCREMENT BY 5
MAXVALUE 15
CYCLE  -- MAXVALUE 범위 안에서 반복 생성함
NOCACHE;

-- 사용
SELECT SEQ2_EMPID.NEXTVAL FROM DUAL;
-- 4회 사용부터 최대값에서 CYCLE 되면 무조건 1부터 시작됨.

-- 시퀀스의 실제 사용 : 발생한 값을 기록하기 위함
CREATE SEQUENCE SEQID
START WITH 300
INCREMENT BY 1
MAXVALUE 310
NOCYCLE  NOCACHE;

INSERT INTO EMPLOYEE (EMP_ID, EMP_NO, EMP_NAME)
VALUES (TO_CHAR(SEQID.NEXTVAL), '811225-1234567', '김영민');

SELECT * FROM EMPLOYEE;

ROLLBACK;

-- 시퀀스 수정
-- ALTER SEQUENCE 시퀀스이름  수정내용;
-- 단, START WITH 항목은 수정 못 함

CREATE SEQUENCE SEQID2
START WITH 300
INCREMENT BY 1
MAXVALUE 310
NOCYCLE  NOCACHE;

SELECT SEQID2.NEXTVAL FROM DUAL;  -- 300
SELECT SEQID2.NEXTVAL FROM DUAL;  -- 301

ALTER SEQUENCE SEQID2
INCREMENT BY 5;

SELECT SEQID2.NEXTVAL FROM DUAL;  -- 306

-- 삭제
-- DROP SEQUENCE 시퀀스이름;
DROP SEQUENCE SEQID2;

-- 확인
SELECT * FROM USER_SEQUENCES;


